[project]
name = "AlmKanal"
version = "0.1.0"
description = "Add a short description here"
authors = ["Fabi <schmidtfa91@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[tasks]

[dependencies]
mne = ">=1.8,<1.9"
pyrasa = ">=1.0.0,<2"