[project]
authors = ["schmidtfa <schmidtfa91@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "SalzWave"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mne = ">=1.8,<1.9"
pyrasa = ">=1.0.0,<2"

